#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$(dirname "$0")")/functions"

APP_OR_GLOBAL="$2"
KEY="$3"
VALUE="$4"

if [[ -z "$APP_OR_GLOBAL" ]] || [[ -z "$KEY" ]]; then
  dokku_log_fail "Usage: dokku review-pg:set <--global|app> <key> [value]"
fi

if [[ "$APP_OR_GLOBAL" == "--global" ]]; then
  APP_OR_GLOBAL="--global"
else
  verify_app_name "$APP_OR_GLOBAL"
fi

if [[ -n "$VALUE" ]]; then
  fn-plugin-property-write "$PLUGIN_NAME" "$APP_OR_GLOBAL" "$KEY" "$VALUE"
  dokku_log_info1 "Set ${KEY} = ${VALUE}"
else
  fn-plugin-property-delete "$PLUGIN_NAME" "$APP_OR_GLOBAL" "$KEY"
  dokku_log_info1 "Deleted ${KEY}"
fi
